import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import http from 'node:http';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.mjs';
import { AuthStore } from '../server/store.mjs';
import { normalizeEmail, encrypt, decrypt, digest, validImage } from '../server/security.mjs';
import { loadConfig } from '../server/config.mjs';
import { createArchiveAdapter } from '../server/adapters/archive.mjs';
import { serializeCart, createLine } from '../src/core.mjs';

const root=fileURLToPath(new URL('..',import.meta.url));
async function setup(t,options={}) {
  let time=Date.now();
  const store=new AuthStore(':memory:');
  const sent=[];
  const config={root,mode:options.mode||'demo',secure:false,secret:randomBytes(32),origin:'http://127.0.0.1',otpTtlMs:600000,sessionTtlMs:1800000,resendMs:60000,maxAttempts:5,...options.config};
  const {server}=createApp(config,{store,now:()=>time,mailer:options.mailer||{async send(message){sent.push(message);}},...(options.archives?{archives:options.archives}:{})});
  server.listen(0,'127.0.0.1');await once(server,'listening');config.origin=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));store.close();});
  function client(){const jar={};let csrf='';return {jar,get csrf(){return csrf;},set csrf(x){csrf=x;},async req(path,method='GET',data,extra={}){
    const response=await fetch(config.origin+path,{method,headers:{Cookie:Object.entries(jar).map(([k,v])=>k+'='+v).join('; '),...(method==='POST'?{Origin:config.origin,'Content-Type':'application/json','X-CSRF-Token':csrf}:{}),...extra},...(data?{body:JSON.stringify(data)}:{})});
    for(const cookie of response.headers.getSetCookie()){const [pair]=cookie.split(';');const at=pair.indexOf('=');jar[pair.slice(0,at)]=pair.slice(at+1);}
    let body;const raw=await response.text();try{body=JSON.parse(raw);}catch{body=raw;}
    if(body?.csrfToken)csrf=body.csrfToken;
    return {status:response.status,body,headers:response.headers,raw};
  }};}
  const c=client();await c.req('/api/session');
  async function login(email='bori@example.test',who=c){const requested=await who.req('/api/auth/request-code','POST',{email});assert.equal(requested.status,200);const code=requested.body.demoCode||sent.at(-1).code;const result=await who.req('/api/auth/verify-code','POST',{challengeId:requested.body.challengeId,code});assert.equal(result.status,200);return result;}
  return {config,store,sent,c,client,login,advance:ms=>{time+=ms;}};
}

test('email + code -> two owned records -> correct selected letter',async t=>{const x=await setup(t);await x.login();const list=await x.c.req('/api/archives');assert.equal(list.status,200);assert.equal(list.body.archives.length,2);assert.ok(!list.raw.includes('letter":'));const detail=await x.c.req('/api/archives/demo-bori-birthday');assert.match(detail.body.archive.letter,/生|생일 축하해/);assert.equal(detail.body.archive.id,'demo-bori-birthday');});
test('unauthenticated email and IDs cannot retrieve archives or images',async t=>{const x=await setup(t);for(const p of ['/api/archives?email=bori@example.test','/api/archives/demo-bori-summer','/api/archives/demo-bori-summer/photos/bori-1'])assert.equal((await x.c.req(p)).status,401);});
test('unknown mailbox follows same request path and becomes empty only after verification',async t=>{const x=await setup(t);await x.login('empty@example.test');const result=await x.c.req('/api/archives');assert.deepEqual(result.body,{archives:[],nextCursor:null});});
test('another owner record is never returned by guessed ID',async t=>{const x=await setup(t);await x.login('nabi@example.test');assert.equal((await x.c.req('/api/archives')).body.archives.length,1);assert.equal((await x.c.req('/api/archives/demo-bori-summer')).status,404);assert.equal((await x.c.req('/api/archives/demo-bori-summer/photos/bori-1')).status,404);});
test('photo IDs are checked within the owned archive',async t=>{const x=await setup(t);await x.login();const valid=await x.c.req('/api/archives/demo-bori-summer/photos/bori-1');assert.equal(valid.status,200);assert.equal(valid.headers.get('content-type'),'image/webp');assert.equal((await x.c.req('/api/archives/demo-bori-birthday/photos/bori-1')).status,404);});
test('unknown/malformed code consumes no session and five failures lock the challenge',async t=>{const x=await setup(t);const r=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});const good=r.body.demoCode;const bad=good==='000000'?'111111':'000000';for(let i=0;i<5;i++)assert.equal((await x.c.req('/api/auth/verify-code','POST',{challengeId:r.body.challengeId,code:bad})).status,400);assert.equal((await x.c.req('/api/auth/verify-code','POST',{challengeId:r.body.challengeId,code:good})).status,400);assert.equal((await x.c.req('/api/archives')).status,401);});
test('OTP is single-use under parallel verification',async t=>{const x=await setup(t);const r=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});const payload={challengeId:r.body.challengeId,code:r.body.demoCode};const responses=await Promise.all([x.c.req('/api/auth/verify-code','POST',payload),x.c.req('/api/auth/verify-code','POST',payload)]);assert.equal(responses.filter(r=>r.status===200).length,1);});
test('OTP is bound to the requesting browser',async t=>{const x=await setup(t);const r=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});const other=x.client();await other.req('/api/session');const result=await other.req('/api/auth/verify-code','POST',{challengeId:r.body.challengeId,code:r.body.demoCode});assert.equal(result.status,400);assert.equal((await other.req('/api/archives')).status,401);});
test('OTP expiration enforced on server',async t=>{const x=await setup(t);const r=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});x.advance(600001);assert.equal((await x.c.req('/api/auth/verify-code','POST',{challengeId:r.body.challengeId,code:r.body.demoCode})).status,400);});
test('resend cooldown is enforced in the API, not only UI',async t=>{const x=await setup(t);assert.equal((await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'})).status,200);const next=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});assert.equal(next.status,429);assert.equal(next.headers.get('retry-after'),'60');});
test('resending invalidates prior browser code',async t=>{const x=await setup(t);const old=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});x.advance(60001);const latest=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});assert.equal((await x.c.req('/api/auth/verify-code','POST',{challengeId:old.body.challengeId,code:old.body.demoCode})).status,400);assert.equal((await x.c.req('/api/auth/verify-code','POST',{challengeId:latest.body.challengeId,code:latest.body.demoCode})).status,200);});
test('hourly per-address budget survives new browser requests',async t=>{const x=await setup(t);for(let i=0;i<5;i++){const c=x.client();await c.req('/api/session');assert.equal((await c.req('/api/auth/request-code','POST',{email:'bori@example.test'})).status,200);x.advance(60001);}const c=x.client();await c.req('/api/session');assert.equal((await c.req('/api/auth/request-code','POST',{email:'bori@example.test'})).status,429);});
test('session expires and cannot be extended by client email claims',async t=>{const x=await setup(t);await x.login();x.advance(1800001);assert.equal((await x.c.req('/api/archives?email=bori@example.test')).status,401);assert.equal((await x.c.req('/api/session')).body.session,null);});
test('logout revokes the server session as well as the browser cookie',async t=>{const x=await setup(t);await x.login();const saved={...x.c.jar};assert.equal((await x.c.req('/api/auth/logout','POST',{})).status,200);Object.assign(x.c.jar,saved);assert.equal((await x.c.req('/api/archives')).status,401);});
test('CSRF token and exact origin enforced',async t=>{const x=await setup(t);const data={email:'bori@example.test'};for(const headers of [{'X-CSRF-Token':'wrong'},{Origin:'https://attacker.invalid'},{Origin:'null'}])assert.equal((await x.c.req('/api/auth/request-code','POST',data,headers)).status,403);});
test('cross-site GET rejected before sensitive response',async t=>{const x=await setup(t);await x.login();assert.equal((await x.c.req('/api/archives','GET',null,{'Sec-Fetch-Site':'cross-site'})).status,403);});
test('host poisoning is rejected',async t=>{const x=await setup(t);const status=await new Promise((resolve,reject)=>{http.get(x.config.origin+'/api/session',{headers:{Host:'attacker.invalid'}},response=>{response.resume();resolve(response.statusCode);}).on('error',reject);});assert.equal(status,403);});
test('private responses are no-store and session cookies are HttpOnly host-only',async t=>{const x=await setup(t);const result=await x.login();assert.match(result.headers.get('cache-control'),/no-store/);const cookie=result.headers.getSetCookie()[0];assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.ok(!cookie.includes('Domain='));assert.ok(!result.raw.includes('bori@example.test'));});
test('server DB contains no plaintext email or OTP',async t=>{const x=await setup(t);const r=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});const rows=x.store.db.prepare('SELECT * FROM challenges').all();assert.ok(!JSON.stringify(rows).includes('bori@example.test'));assert.notEqual(rows[0].code_hash,r.body.demoCode);assert.equal(decrypt(x.config.secret,rows[0].email_cipher),'bori@example.test');});
test('mail failure invalidates the pending OTP and returns a generic message',async t=>{const x=await setup(t,{mailer:{async send(){throw new Error('provider debug secret should never leak');}}});const r=await x.c.req('/api/auth/request-code','POST',{email:'bori@example.test'});assert.equal(r.status,500);assert.ok(!r.raw.includes('secret'));assert.equal(x.store.db.prepare('SELECT count(*) AS count FROM challenges').get().count,0);});
test('live-mode response never contains a developer code',async t=>{const x=await setup(t,{mode:'live',archives:{async list(){return {archives:[],nextCursor:null};}}});const r=await x.c.req('/api/auth/request-code','POST',{email:'real-user@example.com'});assert.equal(r.status,200);assert.equal(r.body.demoCode,undefined);assert.ok(!r.raw.includes(x.sent[0].code));assert.equal(x.sent[0].email,'real-user@example.com');});
test('demo refuses real email addresses',async t=>{const x=await setup(t);assert.equal((await x.c.req('/api/auth/request-code','POST',{email:'user@gmail.com'})).status,400);assert.equal(x.sent.length,0);});
test('upstream failure never becomes a demo record or empty success',async t=>{const x=await setup(t,{archives:{async list(){throw new Error('Upstream down');}}});await x.login();const r=await x.c.req('/api/archives');assert.equal(r.status,500);assert.ok(!r.raw.includes('보리'));assert.ok(!r.raw.includes('archives'));});
test('static server never exposes DB, secrets, server files or encoded traversal',async t=>{const x=await setup(t);for(const p of ['/.env','/server/config.mjs','/.local/auth-demo.sqlite','/docs/README.md','/src/%2e%2e%2fserver%2fconfig.mjs','/assets/%2e%2e%2fserver%2fconfig.mjs'])assert.equal((await x.c.req(p)).status,404,p);assert.equal((await x.c.req('/src/app.mjs')).status,200);assert.equal((await x.c.req('/robots.txt')).status,200);assert.equal((await x.c.req('/sitemap.xml')).status,200);const logo=await x.c.req('/assets/soul-trace-logo.png');assert.equal(logo.status,200);assert.equal(logo.headers.get('content-type'),'image/png');});
test('bad JSON and excessive request size fail closed',async t=>{const x=await setup(t);assert.equal((await x.c.req('/api/auth/request-code','POST',{email:'x'.repeat(9000)})).status,413);assert.equal((await x.c.req('/api/auth/request-code','POST',{email:'a@example.test'},{'Content-Type':'text/plain'})).status,415);});
test('email normalization does not collapse Gmail dots/plus tags or local-part case',()=>{assert.equal(normalizeEmail(' Foo.Bar+pet@EXAMPLE.COM '),'Foo.Bar+pet@example.com');assert.notEqual(normalizeEmail('a.b@example.com'),normalizeEmail('ab@example.com'));assert.throws(()=>normalizeEmail('bad\n@example.com'));});
test('tampered encrypted data is rejected',()=>{const key=randomBytes(32);const cipher=encrypt(key,'private@example.com');assert.equal(decrypt(key,cipher),'private@example.com');const bytes=Buffer.from(cipher,'base64');bytes[20]^=255;assert.throws(()=>decrypt(key,bytes.toString('base64')));});
test('durable SQLite rate limits survive process-store restart',()=>{const dir=mkdtempSync(join(tmpdir(),'st-store-'));try{const path=join(dir,'db.sqlite');let store=new AuthStore(path);store.consumeLimits([{key:'test',max:1,window:60000}],1000);store.close();store=new AuthStore(path);assert.throws(()=>store.consumeLimits([{key:'test',max:1,window:60000}],1001),e=>e.status===429);store.prune(61001);assert.doesNotThrow(()=>store.consumeLimits([{key:'test',max:1,window:60000}],61001));store.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('configuration prevents demo public bind and live mode without verified setup',()=>{const dir=mkdtempSync(join(tmpdir(),'st-config-'));try{assert.throws(()=>loadConfig(dir,{SHOP_MODE:'demo',HOST:'0.0.0.0'}));assert.throws(()=>loadConfig(dir,{SHOP_MODE:'demo',NODE_ENV:'production'}));assert.throws(()=>loadConfig(dir,{SHOP_MODE:'live',APP_ORIGIN:'https://shop.example.com',SHOP_AUTH_SECRET:randomBytes(32).toString('base64')}));const config=loadConfig(dir,{});assert.equal(config.mode,'demo');assert.equal(config.secret.length,32);}finally{rmSync(dir,{recursive:true,force:true});}});
test('archive IDs retained only in tab memory, never localStorage serialization',()=>{const line=createLine('letter','sage',1,{name:'보리',message:'m',letter:'l',photo:'',sourceArchiveId:'private-archive',sourcePhotoId:'private-photo',sourceTitle:'private title'});assert.equal(line.personalization.sourceArchiveId,'private-archive');for(const value of ['private-archive','private-photo','private title'])assert.ok(!serializeCart([line]).includes(value));});
test('image type validation rejects SVG masquerading as PNG',()=>{assert.equal(validImage(Buffer.from('<svg></svg>'),'image/png'),false);assert.equal(validImage(Buffer.from('RIFFxxxxWEBP'),'image/webp'),true);});
